name: Check PR

# Controls when the workflow will run
on:
  pull_request:
    branches:
      - main
    types: [ opened, synchronize, reopened ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  check_size:
    runs-on: ubuntu-latest
    name: Check PR Size
    steps:
      - uses: actions/checkout@v3

      - name: Check Size
        uses: actions/github-script@v6.3.3
        env:
          IGNORED_FILES: openapi.json
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const additions = context.payload.pull_request.additions || 0
            const deletions = context.payload.pull_request.deletions || 0
            var changes = additions + deletions

            const { IGNORED_FILES } = process.env
            const ignored_files = IGNORED_FILES.trim().split(',').filter(word => word.length > 0);
            if (ignored_files.length > 0){
              var ignored = 0
              const execSync = require('child_process').execSync;
              for (const file of IGNORED_FILES.trim().split(',')) {
            
                const ignored_additions = execSync('git --no-pager  diff --numstat | grep ' + file + ' | cut -f 1', { encoding: 'utf-8' })
                const ignored_deletions = execSync('git --no-pager  diff --numstat | grep ' + file + ' | cut -f 2', { encoding: 'utf-8' })
            
                ignored += (parseInt(ignored_additions) + parseInt(ignored_deletions))
              }
              changes -= ignored
            }
            
            if (changes < 150){
              github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ['size/small']
              })
            }
            
            if (changes >= 150 && changes <= 450) {
             github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ['size/medium']
              })
            }

            if (changes > 450){
              github.rest.issues.addLabels({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                labels: ['size/large']
              })
              github.rest.issues.createComment({
                issue_number: context.issue.number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: 'This PR exceeds the recommended size of 450 lines. Please make sure you are NOT addressing multiple issues with one PR. _Note this PR might be rejected due to its size._'
              })
              core.setFailed('PR is too large')
            }

