name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        description: Select the Environment
        options:
          - dev
          - uat
          - prod
          - all
      beta:
        required: false
        type: boolean
        description: deploy beta version on AKS
        default: false

  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: Select the Environment
      beta:
        required: false
        type: boolean
        description: deploy beta version on AKS
        default: false

env:
  NAMESPACE: apiconfig
  APP_NAME: pagopaapiconfig


permissions:
  id-token: write
  contents: read

jobs:
#  deploy:
#    runs-on: ubuntu-latest
#    name: Deploy on AKS
#    strategy:
#      matrix:
#        environment: [ dev, uat, prod ]
#        include:
#          - environment : dev
#            short: d
#          - environment : uat
#            short: u
#          - environment : prod
#            short: p
#    environment:
#      name: ${{ matrix.environment }}
#    steps:
#      - name: Deploy
#        if: ${{ matrix.environment == inputs.environment || inputs.environment == 'all' }}
#        uses: pagopa/github-actions-template/aks-deploy@deploy_aks_beta
#        with:
#          branch: ${{ github.ref_name }}
#          client_id: ${{ vars.CLIENT_ID }}
#          subscription_id: ${{ vars.SUBSCRIPTION_ID }}
#          tenant_id: ${{ vars.TENANT_ID }}
#          env: ${{ matrix.environment }}
#          namespace: ${{ env.NAMESPACE }}
#          cluster_name: pagopa-${{matrix.short}}-weu-dev-aks
#          resource_group: pagopa-${{matrix.short}}-weu-dev-aks-rg
#          app_name: ${{ env.APP_NAME }}
#          helm_upgrade_options: ${{env.OPTIONS}}

  deploy:
    strategy:
      matrix:
        environment: [ dev, uat, prod ]
        include:
          - environment : dev
            short: d
          - environment : uat
            short: u
          - environment : prod
            short: p
    uses: jacopocarlini/check-github-action/.github/workflows/self_hosted.yml@main
    with:
      environment: ${{ inputs.environment }}
      matrix: ${{ matrix.environment }}
      helm_upgrade_options: '--set microservice-chart.canaryDelivery.deployment.image.tag=0.29.1'
    secrets:
      token: ${{secrets.BOT_TOKEN_GITHUB}}
