name: Deploy

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        description: Select the Environment
        options:
          - dev
          - uat
          - prod
          - all
      beta:
        required: false
        type: boolean
        description: deploy beta version on AKS
        default: false

  workflow_call:
    inputs:
      environment:
        required: true
        type: string
        description: Select the Environment
      beta:
        required: false
        type: boolean
        description: deploy beta version on AKS
        default: false

env:
  NAMESPACE: apiconfig
  APP_NAME: pagopaapiconfig


permissions:
  id-token: write
  contents: read

jobs:
#  deploy:
#    runs-on: ubuntu-latest
#    name: Deploy on AKS
#    strategy:
#      matrix:
#        environment: [ dev, uat, prod ]
#        include:
#          - environment : dev
#            short: d
#          - environment : uat
#            short: u
#          - environment : prod
#            short: p
#    environment:
#      name: ${{ matrix.environment }}
#    steps:
#      - name: Deploy
#        if: ${{ matrix.environment == inputs.environment || inputs.environment == 'all' }}
#        uses: pagopa/github-actions-template/aks-deploy@deploy_aks_beta
#        with:
#          branch: ${{ github.ref_name }}
#          client_id: ${{ vars.CLIENT_ID }}
#          subscription_id: ${{ vars.SUBSCRIPTION_ID }}
#          tenant_id: ${{ vars.TENANT_ID }}
#          env: ${{ matrix.environment }}
#          namespace: ${{ env.NAMESPACE }}
#          cluster_name: pagopa-${{matrix.short}}-weu-dev-aks
#          resource_group: pagopa-${{matrix.short}}-weu-dev-aks-rg
#          app_name: ${{ env.APP_NAME }}
#          helm_upgrade_options: ${{env.OPTIONS}}

  deploy_dev:
    if: ${{ inputs.environment == 'dev' || inputs.environment == 'all' }}
    environment:
      name: dev
    uses: jacopocarlini/check-github-action/.github/workflows/deploy_aks_self_hosted.yml@main
    with:
      target: ${{ matrix.target }}
      branch: ${{ github.ref_name }}
      client_id: ${{ vars.CLIENT_ID }}
      subscription_id: ${{ vars.SUBSCRIPTION_ID }}
      tenant_id: ${{ vars.TENANT_ID }}
      env: 'dev'
      namespace: ${{ env.NAMESPACE }}
      cluster_name: pagopa-d-weu-dev-aks
      cluster_resource_group: pagopa-d-weu-dev-aks-rg
      app_name: ${{ env.APP_NAME }}
      helm_upgrade_options: ${{env.OPTIONS}}
      container_app_env: 'github-runner'
      container_resource_group: 'github-runner-rg'
    secrets:
      token: ${{secrets.BOT_TOKEN_GITHUB}}

  deploy_uat:
    if: ${{ inputs.environment == 'uat' || inputs.environment == 'all' }}
    environment:
      name: uat
    uses: jacopocarlini/check-github-action/.github/workflows/deploy_aks_self_hosted.yml@main
    with:
      target: ${{ matrix.target }}
      branch: ${{ github.ref_name }}
      client_id: ${{ vars.CLIENT_ID }}
      subscription_id: ${{ vars.SUBSCRIPTION_ID }}
      tenant_id: ${{ vars.TENANT_ID }}
      env: 'uat'
      namespace: ${{ env.NAMESPACE }}
      cluster_name: pagopa-d-weu-uat-aks
      cluster_resource_group: pagopa-d-weu-uat-aks-rg
      app_name: ${{ env.APP_NAME }}
      helm_upgrade_options: ${{env.OPTIONS}}
      container_app_env: 'github-runner'
      container_resource_group: 'github-runner-rg'
    secrets:
      token: ${{secrets.BOT_TOKEN_GITHUB}}

  deploy_prod:
    if: ${{ inputs.environment == 'prod' || inputs.environment == 'all' }}
    environment:
      name: prod
    uses: jacopocarlini/check-github-action/.github/workflows/deploy_aks_self_hosted.yml@main
    with:
      target: ${{ matrix.target }}
      branch: ${{ github.ref_name }}
      client_id: ${{ vars.CLIENT_ID }}
      subscription_id: ${{ vars.SUBSCRIPTION_ID }}
      tenant_id: ${{ vars.TENANT_ID }}
      env: 'prod'
      namespace: ${{ env.NAMESPACE }}
      cluster_name: pagopa-d-weu-prod-aks
      cluster_resource_group: pagopa-d-weu-prod-aks-rg
      app_name: ${{ env.APP_NAME }}
      helm_upgrade_options: ${{env.OPTIONS}}
      container_app_env: 'github-runner'
      container_resource_group: 'github-runner-rg'
    secrets:
      token: ${{secrets.BOT_TOKEN_GITHUB}}
