name: Update Openapi

# Controls when the workflow will run
on:
  pull_request:
    branches:
      - main
    types: [ opened, synchronize, reopened ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write
  repository-projects: write
  packages: write


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  auto_update:
    name: Update Openapi
    runs-on: ubuntu-latest
    steps:
      - name: Wait for checks
        with:
          ref: ${{ github.sha }}
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          check-regexp: Check.*

      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.ref }}

      - name: Update OpenApi and Swagger files
        run: |
          cd ./openapi
          sh ./generate_openapi.sh

      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--replace"
