name: Update Code

on:
  push:
  workflow_run:
    workflows:
      - Auto Deploy
    types:
      - completed


  workflow_dispatch:

permissions:
  contents: write

jobs:
  openapi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Update OpenApi and Swagger files
        run: |
          cd ./openapi
          sh ./generate_openapi.sh

      - uses: axel-op/googlejavaformat-action@v3
        with:
          args: "--replace"
          files: "**/*"
          commit-message: "Google Java format [skip ci]"

      # prepare openapi template for infra repo
      - run: |
          mkdir -p "${GITHUB_WORKSPACE}/infra"
          jq  '."servers"[0]."url" |= "${host}"' "${GITHUB_WORKSPACE}/openapi/openapi.json" > "${GITHUB_WORKSPACE}/infra/_openapi.json.tpl"

     

